Fix Ivy compatibility issue in Angular 10
ERROR in node_modules/ngx-restangular/lib/ngx-restangular.module.d.ts:8:97 - error TS2314: Generic type 'ModuleWithProviders<T>' requires 1 type argument(s).

ngcc cannot resolve this automatically so code change is required.